---
title: "Midterm"
author: "Michael Clifford and Shuai Wang"
date: "2023-09-29"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(sf)
library(spdep)
library(caret)
library(ckanr)
library(FNN)
library(grid)
library(gridExtra)
library(ggcorrplot)
library(jtools)     # for regression model plots
library(broom)
library(tufte)
library(rmarkdown)
library(kableExtra)
library(tidycensus)
library(tigris)
library(mapview)
library(stargazer)
library(corrr)
library(vtable)
library(sfdep)

# functions and data directory
root.dir = "https://github.com/mafichman/musa_5080_2023.git"

source("https://raw.githubusercontent.com/urbanSpatial/Public-Policy-Analytics-Landing/master/functions.r")

palette5 <- c("#25CB10", "#5AB60C", "#8FA108",   "#C48C04", "#FA7800")

```

```{r qbrNoRound_function}

qBrNoRound <- 
  function(df, variable, rnd) {
  if (missing(rnd)) {
    as.character(quantile(round(df[[variable]],2),
                          c(.01,.2,.4,.6,.8), na.rm=T))
  } else if (rnd == FALSE | rnd == F) {
    as.character(formatC(quantile(df[[variable]],
                                  c(.01,.2,.4,.6,.8), na.rm=T),
                         digits = 3))
  }
}

```

```{r load_key, warning = FALSE, eval = FALSE}
census_api_key("730e334cd384273fdcda9984e41c6444518d82d6", overwrite = TRUE)
```

```{r census_data results='hide'}
varslist = c("B02001_001E",	"B02001_002E",	"B02001_003E",	"B02001_004E",	"B02001_005E",	"B02001_006E",	"B02001_007E",	"B02001_008E",	"B19013_001E",	"B15003_001E",	"B15003_017E",	"B15003_018E",	"B15003_021E",	"B15003_022E",	"B15003_023E",	"B15003_024E",	"B15003_025E",	"B25002_001E",	"B25002_002E",	"B25002_003E",	"B25003_001E",	"B25003_002E",	"B25003_003E")

tracts <-  
  get_acs(geography = "tract",
          variables = varslist, 
          year=2021, state=42,
          county=101, output="wide", geometry=TRUE) %>% 
  st_transform('ESRI:102729')

tracts <- tracts %>% 
  dplyr::select(GEOID, NAME, all_of(varslist))

tracts <- tracts %>%
  rename (TotPop = B02001_001E,	White = B02001_002E,	Black = B02001_003E,	AI = B02001_004E,	
          Asian = B02001_005E,	Pac_il = B02001_006E,	Other_Race = B02001_007E,	
          Multi_Race = B02001_008E,	MedInc = B19013_001E,	Pop25 = B15003_001E,	HS = B15003_017E,	
          GED = B15003_018E,	Assoc = B15003_021E,	Bach = B15003_022E,	Mast = B15003_023E,	
          ProfDeg = B15003_024E,	Doct = B15003_025E,	TotalHouse = B25002_001E,	Occupied = B25002_002E,
          Vacant = B25002_003E,	TotalOcc = B25003_001E,	Own = B25003_002E,	Rent = B25003_003E)


#st_write(tracts, "tracts_shape.shp")

tracts_table <- st_drop_geometry(tracts)
write.csv(tracts_table, file="tracts.csv")

zips = zctas(year = 2010, state = 42)
#st_write(zips, "zipcodes.shp")

comm_vars <- c("B08301_001E",	"B08301_002E",	"B08301_003E",	"B08301_004E",	"B08301_010E",
          "B08301_011E",	"B08301_012E",	"B08301_013E",	"B08301_014E",	"B08301_018E",	"B08301_019E",
          "B08301_021E")

tracts_commute <-  
  get_acs(geography = "tract",
          variables = comm_vars,
          year=2021, state=42,
          county=101, output="wide", geometry=TRUE) %>%
  st_transform('ESRI:102729')

tracts_commute <- tracts_commute %>% 
  dplyr::select(GEOID, NAME, all_of(comm_vars))

tracts_commute <- tracts_commute %>%
  rename (Tot_Comm = B08301_001E,	Auto = B08301_002E,	Auto_Alone = B08301_003E,	Carpool = B08301_004E,
          Transit = B08301_010E,	Bus = B08301_011E,	Subway = B08301_012E,	
          CommRail = B08301_013E,	Trolley = B08301_014E,	Bicycle = B08301_018E,	
          Walked = B08301_019E,	WFH = B08301_021E)
#write.csv(tracts_commute, file="tracts_commute.csv")

ggplot() +
  geom_sf(data = tracts_commute, mapping=aes(fill=CommRail))

```

```{r read_data}
allhouses <- 
  st_read("https://raw.githubusercontent.com/mafichman/musa_5080_2023/main/Midterm/data/2023/studentData.geojson", quiet = TRUE) %>%
  st_transform('ESRI:102729')

houses <- allhouses %>% dplyr::filter(toPredict == "MODELLING")

parks <- 
  st_read("https://opendata.arcgis.com/datasets/d52445160ab14380a673e5849203eb64_0.geojson", 
          quiet = TRUE) %>%
  st_transform('ESRI:102729')

crimes <- 
  read.csv("incidents_part1_part2.csv")

hoods <-
  st_read("Neighborhoods_Philadelphia.shp", 
          quiet = TRUE) %>%
  st_transform('ESRI:102729')

el_catchment <-
  st_read("Catchment_ES_2021-22/Catchment_ES_2021.shp", quiet = TRUE) %>%
  st_transform('ESRI:102729')

stores <- st_read("https://opendata.arcgis.com/datasets/53b8a1c653a74c92b2de23a5d7bf04a0_0.geojson",
                  quiet = TRUE) %>%
  st_transform('ESRI:102729')

```

```{r census_data_clean results='hide'}

varslist = c("B02001_001E",	"B02001_002E", "B15003_001E",	"B15003_022E",	"B15003_023E",	
             "B19013_001E", "B15003_024E",	"B15003_025E",	
             "B25002_001E", "B25002_003E",	"B25003_001E",	"B25003_002E", "B08301_001E",	
             "B08301_003E",	"B08301_010E", "B08301_013E",
             "B08301_018E", "B08301_019E", "B08301_021E")

tracts <-  
  get_acs(geography = "tract",
          variables = varslist, 
          year=2021, state=42,
          county=101, output="wide", geometry=TRUE) %>% 
  st_transform('ESRI:102729')

tracts <- tracts %>% 
  dplyr::select(GEOID, NAME, all_of(varslist))

tracts <- tracts %>%
  rename(TotPop = B02001_001E,	White = B02001_002E,
         MedInc = B19013_001E,
         Pop25 = B15003_001E, Bach = B15003_022E,	Mast = B15003_023E,	
         ProfDeg = B15003_024E,	Doct = B15003_025E,	TotalHouse = B25002_001E, 
         Vacant = B25002_003E,	
         TotalOcc = B25003_001E,	Own = B25003_002E, Tot_Comm = B08301_001E,	
         Auto_Alone = B08301_003E,	Transit = B08301_010E,	
         CommRail = B08301_013E,	Bicycle = B08301_018E, 
         Walked = B08301_019E,	
         WFH = B08301_021E) %>%
  mutate(whitePct = White/TotPop,
         degPct = (Bach+Mast+ProfDeg+Doct)/Pop25,
         vacantPct = Vacant/TotalHouse,
         ownPct = Own/TotalOcc,
         autoPct = Auto_Alone/Tot_Comm,
         transitPct = Transit/Tot_Comm,
         commRailPct = CommRail/Tot_Comm,
         bikePct = Bicycle/Tot_Comm,
         walkPct = Walked/Tot_Comm,
         wfhPct = WFH/Tot_Comm)

```

```{r add_census}

houses <-
  st_intersection(houses, (tracts %>% dplyr::select(whitePct, MedInc, degPct)))


houses <- houses %>% mutate(degPct = replace_na(degPct, 0))

```

```{r crime}

#Filter crimes
# crimes.sf <-
#   crimes %>%
#     filter(text_gener == "Aggravated Assault Firearm" | text_gener == "Aggravated Assault No Firearm",
#            point_y > -1) %>%
#     dplyr::select(geometry) %>%
#     na.omit() %>%
#     distinct()

crimes %>% 
group_by(text_general_code) %>%
  summarize(count = n()) %>%
  arrange(-count) %>% top_n(10) %>%
  kable() %>%
  kable_styling()

crimes.sf <-
  crimes %>%
    filter(text_general_code == "Aggravated Assault Firearm" | text_general_code == "Aggravated Assault No Firearm",
           lat > -1) %>%
    dplyr::select(lat, lng) %>%
    na.omit() %>%
    st_as_sf(coords = c("lng", "lat"), crs = "EPSG:4326") %>%
    st_transform('ESRI:102729') %>%
    distinct()

# Counts of crime per buffer of house sale
houses$crimes.Buffer <- houses %>% 
    st_buffer(660) %>% 
    aggregate(mutate(crimes.sf, counter = 1),., sum) %>%
    pull(counter)

houses <- houses %>% mutate(crimes.Buffer = replace_na(crimes.Buffer, 0))

## Nearest Neighbor Feature
houses <-
  houses %>% 
    mutate(
      crime_nn1 = nn_function(st_coordinates(houses), 
                              st_coordinates(crimes.sf), k = 1),
      
      crime_nn2 = nn_function(st_coordinates(houses), 
                              st_coordinates(crimes.sf), k = 2), 
      
      crime_nn3 = nn_function(st_coordinates(houses), 
                              st_coordinates(crimes.sf), k = 3), 
      
      crime_nn4 = nn_function(st_coordinates(houses), 
                              st_coordinates(crimes.sf), k = 4), 
      
      crime_nn5 = nn_function(st_coordinates(houses), 
                              st_coordinates(crimes.sf), k = 5))

```

```{r catchment, warning=FALSE}

houses <-
  st_intersection(houses, (el_catchment %>% dplyr::select(ES_ID)))

```

```{r neighborhood, warning=FALSE}

houses <-
  st_intersection(houses, (hoods %>% dplyr::select(NAME)))

```


```{r high_produce_stores, warning=FALSE}

stores$prodRatio <- stores$TOTAL_HPSS/stores$TOTAL_LPSS 

houses <-
  st_intersection(houses, (stores %>% dplyr::select(prodRatio, TOTAL_LPSS, TOTAL_HPSS)))

houses <- houses %>% mutate(prodRatio = replace_na(prodRatio, 0))

```

```{r parks}

#parksPt <- st_centroid(parks)

parks4buff <- parks %>% dplyr::select(geometry)

#parks within 1/2 mile
houses$parks.Buffer <- houses %>% 
    st_buffer(2640) %>% 
    aggregate(mutate(parks4buff, counter = 1),., sum) %>%
    pull(counter)

houses <- houses %>% mutate(parks.Buffer = replace_na(parks.Buffer, 0))

```

```{r neighbor_prices}

houses <- houses %>% 
          mutate(nb = st_knn(geometry, k = 5),
                 wt = st_weights(nb),
                 price_lag = st_lag(sale_price, nb, wt))

```

```{r summary_table}

allNumVars <- 
  st_drop_geometry(houses) %>%
  dplyr::select(sale_price, total_livable_area, year_built, exterior_condition, fireplaces, 
                frontage, garage_spaces, interior_condition, total_livable_area,  
                crimes.Buffer, crime_nn1, crime_nn2, crime_nn3, crime_nn4, crime_nn5, 
                parks.Buffer, prodRatio, TOTAL_LPSS, TOTAL_HPSS, price_lag, degPct)

qualVars <- 
  st_drop_geometry(houses) %>%
  dplyr::select(sale_price, building_code_description_new, quality_grade, view_type, ES_ID,
                 NAME)

stargazer(allNumVars, omit.summary.stat = "N", type = "text", title = "Summary Statistics")

qualVars %>% group_by(quality_grade) %>%
  summarize(meanPrice = mean(sale_price)) %>% 
  kable() %>%
  kable_styling(bootstrap_options = "striped")

qualVars %>% group_by(building_code_description_new) %>%
  summarize(meanPrice = mean(sale_price)) %>% 
  kable() %>%
  kable_styling(bootstrap_options = "striped")

```

```{r correlation_matrix, message = FALSE}
numericVars <- 
  select_if(st_drop_geometry(houses), is.numeric) %>%
  dplyr::select(sale_price, total_livable_area, year_built, exterior_condition, fireplaces, 
                frontage, garage_spaces, interior_condition, total_livable_area, degPct, 
                crimes.Buffer, crime_nn1, crime_nn2, crime_nn3, crime_nn4, crime_nn5, 
                parks.Buffer, prodRatio, TOTAL_LPSS, TOTAL_HPSS, price_lag) %>%
  na.omit()

ggcorrplot(
  round(cor(numericVars), 1), 
  p.mat = cor_pmat(numericVars),
  colors = c("#25CB10", "white", "#FA7800"),
  type="lower",
  insig = "blank") +  
    labs(title = "Correlation across numeric variables") 

# yet another way to plot the correlation plot using the corrr library
numericVars %>% 
  correlate() %>% 
  autoplot() +
  geom_text(aes(label = round(r,digits=2)),size = 2) +
  labs(caption = "Figure 1: Correlation Matrix of Numeric Variables")

```

```{r correlation_scatterplots, warning=FALSE}

st_drop_geometry(houses) %>% 
  dplyr::select(sale_price, total_livable_area, TOTAL_HPSS, price_lag, crime_nn3) %>%
  filter(sale_price <= 1000000, houses$year_built > 1523, total_livable_area < 10000,
         price_lag<=1000000) %>%
  gather(Variable, Value, -sale_price) %>% 
   ggplot(aes(Value, sale_price)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     facet_wrap(~Variable, ncol = 3, scales = "free") +
     labs(title = "Price as a function of continuous variables",
          caption = "Figure 2: Correlation Scatterplots for Selected Variables") +
     plotTheme()

```

```{r variable_maps}

#parks.Buffer
ggplot() +
  geom_sf(data = hoods, fill = "grey50") +
  geom_sf(data = houses, aes(colour = q5(parks.Buffer)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(houses,"parks.Buffer"),
                   name="Quintile\nBreaks") +
  labs(title="PPR Parks within 1/2 Mile, Philadelphia") +
  mapTheme()

#crime_nn3
ggplot() +
  geom_sf(data = hoods, fill = "grey50") +
  geom_sf(data = houses, aes(colour = q5(crime_nn3)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(houses,"crime_nn3"),
                   name="Quintile\nBreaks") +
  labs(title="K=3 Nearest Neighbor Score\nfor Aggravated Assault, Philadelphia") +
  mapTheme()

```

```{r price_map}

## Plot sale price (modelling) 

ggplot() +
  geom_sf(data = hoods, fill = "grey40") +
  geom_sf(data = houses, aes(colour = q5(sale_price)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(houses,"sale_price"),
                   name="Quintile\nBreaks") +
  labs(title="sale price") +
  mapTheme()

```

```{r retail map}

ggplot()+
  geom_sf(data = stores, aes(fill = TOTAL_LPSS),
          color = "transparent")+
  labs(
    title = "Number of Low-Produce Stores",
    subtitle = "",
    caption = "Data: ") +
  mapTheme()

ggplot()+
  geom_sf(data = stores, aes(fill = TOTAL_HPSS),
          color = "transparent")+
  labs(
    title = "Number of High-Produce Stores",
    subtitle = "",
    caption = "Data: ") +
  mapTheme()



ggplot()+
  geom_sf(data = hoods, fill = "grey50") +
  geom_sf(data = stores, aes(fill = q5(prodRatio)))+
  scale_fill_manual(values = palette5,
                   labels=qBrNoRound(stores,"prodRatio"),
                   name="Quintile\nBreaks") + 
  labs(
    title = "High- and Low-produce ratio",
    subtitle = "",
    caption = "Data: ") + 
  mapTheme()

```


```{r regression_test, warning=FALSE}

inTrain <- createDataPartition(
              y = paste(houses$building_code_description_new, houses$quality_grade,
                        houses$view_type, houses$ES_ID, houses$NAME), 
              p = .60, list = FALSE)
houses.training <- houses[inTrain,] 
houses.test <- houses[-inTrain,]  
 
reg.training <- 
  lm(houses.training$sale_price ~ ., data = as.data.frame(houses.training) %>% 
                             dplyr::select(total_livable_area,  exterior_condition,
                                           fireplaces, 
                                           interior_condition, total_livable_area,
                                           crime_nn3, parks.Buffer, prodRatio,
                                           degPct, price_lag,
                                           building_code_description_new,
                                           view_type))

summ(reg.training)

houses.test <-
  houses.test %>%
  mutate(Regression = "Baseline Regression",
         sale_price.Predict = predict(reg.training, houses.test),
         sale_price.Error = sale_price.Predict - sale_price,
         sale_price.AbsError = abs(sale_price.Predict - sale_price),
         sale_price.APE = (abs(sale_price.Predict - sale_price)) / sale_price.Predict)%>%
  filter(sale_price < 5000000) 


houses.test %>% 
  st_drop_geometry() %>%
  summarize(MAE = mean(sale_price.AbsError, na.rm = T),
            MAPE = mean(sale_price.APE, na.rm = T)) %>%
  gather(Variable, Value) %>%
  mutate(Value = round(Value, 2)) %>%
  kable() %>%
  kable_styling(bootstrap_options = "condensed", full_width = F)
```

```{r cross_validation}

fitControl <- trainControl(method = "cv", number = 100)
set.seed(825)

reg.cv <- 
  train(sale_price ~ ., data = st_drop_geometry(houses) %>% 
                                dplyr::select(sale_price, total_livable_area, 
                                              exterior_condition,
                                              fireplaces, interior_condition,
                                              total_livable_area,
                                              crime_nn3, parks.Buffer, prodRatio,
                                              degPct, price_lag,
                                              building_code_description_new,
                                              view_type), 
     method = "lm", trControl = fitControl, na.action = na.pass)

reg.cv
ggplot(reg.cv$resample, aes(x=MAE)) +
  geom_histogram(fill = "#FA7800", color = "white") +
  labs(
    title = "MAE",
    subtitle = "",
    caption = "Figure:")
```

```{r price_comparison, warning=FALSE}

st_drop_geometry(houses.test) %>% 
  dplyr::select(sale_price, sale_price.Predict) %>%
  filter(sale_price <= 1000000, sale_price.Predict <=1000000) %>%
  ggplot(aes(sale_price, sale_price.Predict)) +
     geom_point(size = .5) + geom_smooth(method = "lm", se=F, colour = "#FA7800") +
     labs(title = "Predicted Sales Price as a Function of Observed Price",
          caption = "Figure 2: Correlation Scatterplots for Selected Variables") +
     plotTheme()

```

```{r residual_map}

ggplot() +
  geom_sf(data = hoods, fill = "grey50") +
  geom_sf(data = houses.test, aes(colour = q5(sale_price.AbsError)), 
          show.legend = "point", size = .75) +
  scale_colour_manual(values = palette5,
                   labels=qBr(houses.test,"sale_price.AbsError"),
                   name="Quintile\nBreaks") +
  labs(title="APE") +
  mapTheme()


#Moran's I
coords <- st_coordinates(houses) 

neighborList <- knn2nb(knearneigh(coords, 5))

spatialWeights <- nb2listw(neighborList, style="W")

houses$lagPrice <- lag.listw(spatialWeights, houses$sale_price)

coords.test <-  st_coordinates(houses.test) 

neighborList.test <- knn2nb(knearneigh(coords.test, 5))

spatialWeights.test <- nb2listw(neighborList.test, style="W")

testAE <- 
  houses.test %>%
  dplyr::select(sale_price.Predict, sale_price.AbsError)

houses.inf <- !is.infinite(houses.test)

houses.test %>% 
  mutate(lagPriceError = lag.listw(spatialWeights.test, sale_price.AbsError)) %>%
  ggplot()+
  geom_point(aes(x =lagPriceError, y = sale_price.AbsError))

moranTest <- moran.mc(houses.test$sale_price.AbsError, 
                      spatialWeights.test, nsim = 999, na.action = na.omit)
 
ggplot(as.data.frame(moranTest$res[c(1:999)]), aes(moranTest$res[c(1:999)])) +
  geom_histogram(binwidth = 0.01) +
  geom_vline(aes(xintercept = moranTest$statistic), colour = "#FA7800",size=1) +
  scale_x_continuous(limits = c(-1, 1)) +
  labs(title="Observed and permuted Moran's I",
       subtitle= "Observed Moran's I in orange",
       x="Moran's I",
       y="Count") +
  plotTheme()

```